name: Build silta cli binary and attach to test release

on:
  push:
    branches: [ feature/* ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests-matrix:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Run tests
        run: go test -v ./tests
  releases-matrix:
    name: Cross compile and release Go Binaries
    runs-on: ubuntu-latest
    needs: tests-matrix
    strategy:
      matrix:
        # Release unsigned darwin binaries
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: wangyoucao577/go-release-action@v1.24
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: test
          overwrite: true
          goversion: "https://go.dev/dl/go1.17.6.linux-amd64.tar.gz"
          binary_name: "silta"
          ldflags: "-X github.com/wunderio/silta-cli/internal/common.Version=${{ steps.vars.outputs.sha_short }}"
  circleci-k8s-test-build:
    name: Test builds with released CLI
    runs-on: ubuntu-latest
    needs: releases-matrix
    steps:
      - uses: actions/checkout@v2
      - name: Validate released cli with drupal-project-k8s
        run: |
          CIRCLECI_DEV_API_TOKEN="${{ secrets.CIRCLECI_DEV_API_TOKEN }}"
          REPO_NAME="drupal-project-k8s"
          JOB_COUNT=4
          source "${GITHUB_WORKSPACE}/.github/circleci-k8s-test-build.sh"
      - name: Validate released cli with frontend-project-k8s
        run: |
          CIRCLECI_DEV_API_TOKEN="${{ secrets.CIRCLECI_DEV_API_TOKEN }}"
          REPO_NAME="frontend-project-k8s"
          JOB_COUNT=4
          source "${GITHUB_WORKSPACE}/.github/circleci-k8s-test-build.sh"
      - name: Validate released cli with simple-project-k8s
        run: |
          CIRCLECI_DEV_API_TOKEN="${{ secrets.CIRCLECI_DEV_API_TOKEN }}"
          REPO_NAME="simple-project-k8s"
          JOB_COUNT=3
          source "${GITHUB_WORKSPACE}/.github/circleci-k8s-test-build.sh"
